# Generated by Django 2.1.1 on 2018-11-23 00:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181123_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 0, 46, 26, 614604, tzinfo=utc)),
        ),
    ]
